# Include
INCLUDE(sarturis-gtk)
INCLUDE(sarturis-python)

# PYGOBJECT
PKG_CHECK_MODULES(PYGOBJECT pygobject-2.0)
INCLUDE_DIRECTORIES(${PYGOBJECT_INCLUDE_DIRS})
LINK_DIRECTORIES(${PYGOBJECT_LIBRARY_DIRS})
SET(PYGTK_LIBS ${PYGOBJECT_LIBRARIES})
