# pkg-config
FIND_PACKAGE(PkgConfig)

# GTK 3.0 ansonsten GTK 2.0
IF(NOT GTK_FOUND)
  PKG_CHECK_MODULES(GTK gtk+-3.0)
  IF(GTK_FOUND)
    SET(GTK_VERSION_GTK3 1 CACHE INTERNAL "gtk 3 found")
    SET(GTK_VERSION_GTK2 0 CACHE INTERNAL "gtk 2 not found")
  ELSE(GTK_FOUND)
    SET(GTK_VERSION_GTK3 0 CACHE INTERNAL "gtk 3 not found")
    SET(GTK_VERSION_GTK2 1 CACHE INTERNAL "gtk 2 found")
    PKG_CHECK_MODULES(GTK gtk+-2.0)
  ENDIF(GTK_FOUND)
ENDIF(NOT GTK_FOUND)

# Flags
IF(GTK_VERSION_GTK3)
  ADD_DEFINITIONS(-DSARTURIS_GTK3)
ENDIF(GTK_VERSION_GTK3)

IF(GTK_VERSION_GTK2)
  ADD_DEFINITIONS(-DSARTURIS_GTK2)
ENDIF(GTK_VERSION_GTK2)

# Verzeichnisse
INCLUDE_DIRECTORIES(${GTK_INCLUDE_DIRS})
LINK_DIRECTORIES(${GTK_LIBRARY_DIRS})
