# Include
INCLUDE(sarturis-gtk)
INCLUDE(sarturis-python)

# PYGTK oder PYGOBJECT
IF(GTK_VERSION_GTK2)
  PKG_CHECK_MODULES(PYGTK pygtk-2.0)
  INCLUDE_DIRECTORIES(${PYGTK_INCLUDE_DIRS})
  LINK_DIRECTORIES(${PYGTK_LIBRARY_DIRS})
  SET(PYGTK_LIBS ${PYGTK_LIBRARIES})
ELSE(GTK_VERSION_GTK2)
  PKG_CHECK_MODULES(PYGOBJECT pygobject-2.0)
  INCLUDE_DIRECTORIES(${PYGOBJECT_INCLUDE_DIRS})
  LINK_DIRECTORIES(${PYGOBJECT_LIBRARY_DIRS})
  SET(PYGTK_LIBS ${PYGOBJECT_LIBRARIES})
ENDIF(GTK_VERSION_GTK2)
